name: "Setup Java + Cache Maven"
description: "Sets up JDK and caches Maven deps"

inputs:
  TEST_INPUT:
    description: "This is a test input"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "21"

    - uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-${{ runner.os }}-

    - name: Test Input
      shell: bash
      run: |
        echo "This is test input: ${{ inputs.TEST_INPUT }}"
        echo "This is test environment variable: ${ENV_INPUT}"
